### DISCUSSION TITLE
Vertx Pg Client And Flyway

### DISCUSSION THREAD

**Discussion by hantsy** [micronaut-projects/micronaut-sql#1330] [Q&A]
I have tried flyway with data jpa/jdbc/r2dbc etc, it seems it worked well. But today I created an example project with RxJava3 and Vertx Pg Client, it seems Flyway does not work as expected, the vertx pg client connect to db too early.

The example project: https://github.com/hantsy/micronaut-sandbox/tree/master/rxjava3-vertx-pg-client

And flyway dependencies:

```kotlin
//flyway
implementation("io.micronaut.flyway:micronaut-flyway")
runtimeOnly("org.flywaydb:flyway-database-postgresql")
runtimeOnly("org.postgresql:postgresql:42.7.3")
```

And flyway configuration:

```yaml
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/blogdb
    driverClassName: org.postgresql.Driver
    username: user
    password: password
    schema-generate: NONE
    dialect: POSTGRES
    db-type: postgres
flyway:
  datasources:
    default:
      enabled: true
      baseline-version: 0
      baseline-on-migrate: true
```
