### DISCUSSION TITLE
Hikari Pool

### DISCUSSION THREAD

**Discussion by powerserg19** [micronaut-projects/micronaut-sql#1490] [Q&A]
I am trying to figure out how to pause  HikariPool from trying to connect to my DB until I load my password
Hikari pool is the VERY  first thing that runs when my app runs
```
Micronaut (v3.10.4)

2024:11:14T15:14:13.584 [main] INFO  i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment - Established active environments: [oraclecloud, cloud]
2024:11:14T15:14:13.810 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
```

My Micronaut 3.10 application uses implementation 'io.micronaut.sql:micronaut-jdbc-hikari:v6.0.0' 

My Crud Repository class is this

```
@JdbcRepository(dialect = Dialect.MYSQL)
public interface LogResultsRepository extends CrudRepository<LogResults, Long> {

}

```

My Mapped Entity 

```
@Data
@Serdeable
@MappedEntity
public class LogResults {
    @Id
    @GeneratedValue(GeneratedValue.Type.AUTO)
    private Long id;
    @NonNull
    private Integer LogFiles = 0;
```

I have tried various setting in my  application.yml to delay it but nothing seems to work
```
datasources:
 default:
    url: ${MYSQL_DB:`jdbc:mysql://127.0.0.1:3306/metrics`}
    username: ${DB_USERNAME:`xxxx`}
    password: ${DB_PASSWORD:`xxxx`}
    driverClassName: ${DRIVER_CLASS:`com.mysql.cj.jdbc.Driver`}
    dialect: MYSQL
    auto-commit: true
    hikari:
      enabled: ${DB_ENABLED:false}
      initializationFailTimeout: -1
      minimumIdle: 0
      connectionTimeout: 30000
```

What is the approach to to having Hikari either wait for my bean to load the password or manually control Hikari myself. I tried the  latter but then i get not backing repository config exists.
If I run my app in my IDE my Bean class that loads the passwords runs before Hikari. If I run the jar that is not the case

Please Help!
