### ISSUE TITLE
When I use Jpa Specification - Unexpected error occurred: Could not obtain transaction-synchronized Session for current thread

### ISSUE THREAD

**Issue by wangdiskater** [micronaut-projects/micronaut-sql#137]
I find 
```
Object value = TransactionSynchronizationManager.getResource(this.sessionFactory);
```
value is null. throw this exception.
Application Start,
```
        additionalSettings.put(AvailableSettings.CURRENT_SESSION_CONTEXT_CLASS, MicronautSessionContext.class.getName());
```
And using default sessionFactory. However,
In application.xml I set 'current_session_context_class' .its doesn"t work.
```
jpa:
  default:
    entity-scan:
      packages:
        - 'jpatest.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        current_session_context_class: thread
```

## Service
```
@Singleton
public class BookService {

    @Inject
    BookRepository bookRepository;
    
    @Transactional()
    public HttpResponse findAll() {
        List all = bookRepository.findAll(BookSpecifications.findGreaterThan());
        return HttpResponse.ok(all);
    }
}
```
## Repository
```
@Repository
@Transactional
public interface BookRepository extends CrudRepository<Book, Long>,JpaSpecificationExecutor<Book> {
    Book find(String title);
}
```
## Specification
```
public class BookSpecifications {
    public static Specification<Book> findGreaterThan() {
        return (Specification<Book>) (root, query, criteriaBuilder) -> criteriaBuilder.greaterThan(root.get(Book_.id), (long) 1);
    }
}
```
I don't know why?

**Comment by wangdiskater** [comment]
In the package io.micronaut.data:micronaut-data-spring-jpa:1.0.1 this method:
````
io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean#hibernateStandardServiceRegistry
......
additionalSettings.put(
                AvailableSettings.CURRENT_SESSION_CONTEXT_CLASS,
                "org.springframework.orm.hibernate5.SpringSessionContext");
````
I set application.xml about `current_session_context_class: thread`. it doesn‘t work and alway is 'org.springframework.orm.hibernate5.SpringSessionContext'
```
jpa:
  default:
    properties:
      hibernate:
        current_session_context_class: thread
        hbm2ddl:
          auto: update
        show_sql: false
```
So i can't create ThreadLocalSessionContext in SessionFactoryImp
```
String impl = (String) properties.get( Environment.CURRENT_SESSION_CONTEXT_CLASS );
else if ( "thread".equals( impl ) ) {
    return new ThreadLocalSessionContext( this );
}
```
