### ISSUE TITLE
Set Oracle client name from `micronaut.application.name` property

### ISSUE THREAD

**Issue by mikehearn** [micronaut-projects/micronaut-sql#1446]
### Feature description

Micronaut has a global application name concept. Oracle connections can be given a session name that shows up in various places (e.g. when listing active sessions). It is easy to set:

```
datasources:
  default:
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    driver-class-name: oracle.jdbc.OracleDriver
    username: abc
    password: abc
    dialect: oracle
    data-source-properties:
      v$session.program: "My Great Program"
```

.... but not _intuitive_ to set. Micronaut SQL should configure this data source property when the dialect is `oracle` by itself so everything just works.
