### ISSUE TITLE
MAJOR: Hibernate configuration from application.yaml is not taken into account

### ISSUE THREAD

**Issue by donarus** [micronaut-projects/micronaut-sql#723]
### My setup
Micronaut 3.6.3 with micronaut-data-hibernate-jpa

Part of our **application.yaml** which worked prior upgrade

```yaml
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
```

After upgrade from Micronaut 3.5.5 (which uses older micronaut-data version) to Micronaut 3.6.3, it started to fail on error

```
18:29:13.974 [server-event-loop-nioEventLoopGroup-3-2] DEBUG o.h.e.jdbc.spi.SqlExceptionHelper - could not extract ResultSet [n/a]
org.postgresql.util.PSQLException: ERROR: column tenant0_.createdat does not exist
  Hint: Perhaps you meant to reference the column "tenant0_.created_at".
  Position: 32
```

So I tried to add the correct strategy to application.yaml (although it should be a default)

```yaml
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        physical_naming_strategy: io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy
```

but without effect. So i was debugging and digging and found the following lines of code, which were changed recently

```java
    public JpaConfiguration copy(String name) {
        JpaConfiguration jpaConfiguration = new JpaConfiguration(name, integrator, applicationContext, entityScanConfiguration);
        jpaConfiguration.setProperties(new HashMap<>(jpaConfiguration.getProperties()));
        jpaConfiguration.setMappingResources(new ArrayList<>(jpaConfiguration.getMappingResources()));
        jpaConfiguration.setCompileTimeHibernateProxies(compileTimeHibernateProxies);
        jpaConfiguration.setReactive(reactive);
        return jpaConfiguration;
    }
``` 

see https://github.com/micronaut-projects/micronaut-sql/blob/v4.6.3/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L293-L300

In my opinion, this is invalid, because this method should copy the jpa properties loaded from application yaml and copy it. And Ithink it uses an invalid source object for copying. In my opinion, the method should be 

```java
    public JpaConfiguration copy(String name) {
        JpaConfiguration jpaConfiguration = new JpaConfiguration(name, integrator, applicationContext, entityScanConfiguration);
        jpaConfiguration.setProperties(new HashMap<>(getProperties())); // changed from jpaProperties.getProperties() to getProperties()
        jpaConfiguration.setMappingResources(new ArrayList<>(getMappingResources())); // changed from jpaProperties.getMappingResources() to getMappingResources()
        jpaConfiguration.setCompileTimeHibernateProxies(compileTimeHibernateProxies);
        jpaConfiguration.setReactive(reactive);
        return jpaConfiguration;
    }
```

If I'm correct, this seems like a major BUG because it does not matter if user configures his own JPA section in application.yaml or if she relies on the default one - this will always "clear" the configuration properties to an empty hashmap.
