### ISSUE TITLE
Passing additional parameters to jdbc connection

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-sql#810]
### Feature description

_Not sure if bug or feature_

I'm using hikari and postgresql. You can pass additional params via ugly jdbc URL:
```
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db?-c%20my.var=SOMEVAL%20-c%20pg_trgm.similarity_threshold=0.1
```
I assumed that I can do instead
```
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db
    options: -c my.var=SOMEVAL -c pg_trgm.similarity_threshold=0.1
```
or even better
```
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db
    options:
     - -c my.var=SOMEVAL
     - -c pg_trgm.similarity_threshold=0.1
```
and all unknown params will be url encoded and attached to jdbc url but It doesn't work.
